- build/webvr-polyfill.js
We are using wasd to move the camera around. We need to disable the wasd keycode binding. What do you guys think?
> Free wasd key for camere movement

- README.md
- src/fusion-position-sensor-vr-device.js
I'm using the head tracking functionality and it works great. On the same project I'm also implementing my own touch controls and the builtin `touch panner` conflicts with them. I would like to have a flag to disable them.
> Flag to disable touch panner in fusion sensor mode

- README.md
- src/webvr-polyfill.js
This is similar to my previous https://github.com/borismus/webvr-polyfill/pull/18
I have my own mouse and keyboard controls and ```MouseKeyboardPositionSensorVRDevice``` is conflicting with them. I would like to have the option to disable them. If you want to handle this differently let me know and I will update the PR.
> Flag to disable MouseKeyboardPositionSensorVRDevice

- Makefile
Thanks for your hard work. Your library has been very useful. I'm running into a problem when using your module within a project that also uses browserify. It's unfortunate that browserified dependencies don't play well within a browserified project! The parser looks for the require calls in all the modules (including external dependencies) and tries to resolve them. We end up with a bunch of `Cannot find module XXX.js` errors. That's an old issue that as far as I know hasn't been solved yet. There's a discussion going here: https://github.com/substack/node-browserify/pull/1151
On your side, you can run your build through [derequire](https://www.npmjs.com/package/derequire) to make it easier to consume. [derequire](https://www.npmjs.com/package/derequire) renames the `require` calls to …
> Derequires build to be friendly with browserified projects

- build/webvr-polyfill.js
- src/cardboard-distorter.js
Patched several functions like gl.enable/disable to track the state as
it’s changed which means we don’t need to call getParameters to find
out their state during distortion. Didn’t patch the binding functions,
but they’re state saving can be bypassed with a config flag and doesn’t
seem to be making a big impact on perf anyway. On my Nexus 5X this
takes average frame rates from ~35fps to ~45-50fps. Allowed me to bump
the buffer scale on the WebVR samples up to 0.75 from 0.5 and still
maintain 60FPS.
> Drastically reduce number of getParameter calls needed per frame

- build/webvr-polyfill.js
- src/cardboard-distorter.js
- src/cardboard-ui.js
- src/util.js
I don't have an iOS device with me to test this with, sadly, but I think it should avoid the problems we're seeing in Issue #46. (I was at least able to test it on desktop Safari.) It no longer patches the canvas width and height in Safari and instead checks the values each `submitFrame` and resizes the framebuffer when needed. This will cause some minor quality and perf issues but prevent larger correctness ones. Also forces the backbuffer to clear every `submitFrame`, which should prevent the white background we're seeing. I also took the liberty of doing a minor optimization to the `Util.is...` functions, since they're going to get called a lot more frequently now and their return value should never change.
*Please test this on an iOS device before merging!*
> Taking a stab at fixing some iOS issues.

- build/webvr-polyfill.js
- package.json
- src/base.js
This brings it in line with the latest iteration of the spec. Preserved
the ability to supply a single layer as well, but doing so will display
a warning about using the deprecated form of the API.
Sorry that the build version has so many changes. Guess I just got a newer version of browserify.
> Update requestPresent to accept an array of layers

- src/distortion/distortion.js
This allows approximate inverse distortion coefficients to be calculated from a headset's specified distortion coefficients, so that headsets can be specified without having them precomputed (as they're specified in #73).
> Add approximateInverse function for inverse distortion coefficients

- README.md
- build/webvr-polyfill.js
- src/cardboard-distorter.js
- src/cardboard-vr-display.js
- src/main.js
We're handling UX in a different way and we need to override the default one. These pieces might better placed in https://github.com/borismus/webvr-boilerplate. IMO, the webvr-polyfill should just polyfill the API and not be opinionated about UX flows.
> Add flags to disable rotation instructions and ui on stereo mode

- build/webvr-polyfill.js
- src/cardboard-vr-display.js
[This commit](https://github.com/borismus/webvr-polyfill/commit/dda3c4b51cda0e307b8c168a392bd7e4f423729d) introduced a typo that makes the cardboard UI not listen on clicks.
> Fix typo that disables listening on cardboard UI clicks

- src/base.js
- if screen.orientation.lock() fails, catch the error. 
thus it doesnt trigger an exception in js console. 
im not sure it is a bug. But when i launch webvr-polyfill in chrome desktop and toggle 'device mode' in devtools, this exception is triggered everytime you goto to vr mode.
> fix orientation.lock() error handling

- build/webvr-polyfill.js
- src/base.js
- src/cardboard-vr-display.js
- support calls to `requestPresent` when already presenting, to update layer config
- update distorter dimensions on vrdisplaypresentchange
- copy VRLayer config so it's not accidentally overwritten
There is a test example here http://output.jsbin.com/fohuqen
I have submitted a [pull request at three.js](https://github.com/mrdoob/three.js/pull/9290) to make `VREffect` correctly handle changing `VRLayer` bounds, and the example above uses that code. However, this pull request is not strictly dependent on it, so you shouldn't need to wait for the next three.js to merge.
> Support VRLayer bounds configuration

- build/webvr-polyfill.js
- src/webvr-polyfill.js
Refer to the [spec](https://w3c.github.io/webvr/#navigator-vrenabled-attribute)
This will be necessary when running a webvr page inside an iframe that may or may not have the appropriate permissions to access webvr devices. The iframe needs to detect when it does not have permission so it can pop out into a new window or otherwise notify the user that VR is not supported.
Because of the nature of the polyfill, this behaves a little bit differently from the native implementation. Natively, `navigator.vrEnabled` requires an iframe to have the `allowvr` attribute set, but since the polyfill uses full screen instead, in this case it will require the `allowfullscreen` attribute (and/or prefixed alternatives for older browser versions).
Note: Currently, neither Firefox nor Chromium implements …
> Implement navigator.vrEnabled

- src/cardboard-distorter.js
Fixes issues when using with PlayCanvas with device pixel ratio.
Seems be due to us resizing the canvas after the patch is applied which is then not passed on to the actual canvas.
Fixes #130
> Resize the real canvas through the patched canvas width/height properties

- build/webvr-polyfill.js
- src/util.js
The function `mat4_invert` was being assigned to a variable that was not declared, causing errors when in strict mode. It caused me problems when importing the module with Rollup.
> Fixed error in strict mode

- src/sensor-fusion/fusion-pose-sensor.js
Hey, great work on the polyfill! I'm using just the pose sensor part of the project at the moment which is really useful but I noticed it carries on listening for motion events after it's destroyed so I've added a method to stop or start them again. Hopefully you find it useful, let me know your thoughts.
Thanks,
Al
> Add ability to remove event listeners on FusionPoseSensor.js

- build/webvr-polyfill.js
- src/main.js
- src/webvr-polyfill.js
Added modes that allow the polyfill to continue working even when the
native API is present. Dev’s can choose “NO_NATIVE_API” for the
existing behavior (this is the default), “NO_NATIVE_DISPLAY” to have
the polyfill kick in when the native API is present but doesn’t provide
a display, and “ALWAYS” to always have a polyfilled VRDisplay appended
to the returned list.
> Added two new modes to the polyfill

- src/dpdb/dpdb-cache.js
Added device settings for:
- Samsung S7 Edge
- Motorola Moto G4
- Google Pixel
- iPhone 6s+
These settings have been confirmed as working on various GH issue threads in the WebVR boilerplate and A-Frame repos.
Also, removed duplicate entries for iOS devices.
For some background see:
https://github.com/aframevr/aframe/issues/2008
https://github.com/aframevr/aframe/issues/2117
This PR is focused on issue [2117](https://github.com/aframevr/aframe/issues/2117) in particular.
> Add Pixel, S7 Edge, 6s+, clean up iOS doubles

- src/base.js
- src/cardboard-vr-display.js
In #135, we added support for configuring VRLayer bounds on the fly by calling `requestPresent` even after presentation has started. This feature was broken by ed61b1dfdfcee26b68b0fb4b5cd52d949bdce45f, which stopped layer changed from firing an event, per the spec at the time (I think).
This commit restores the feature by updating layer bounds every time `submitFrame` is called, without firing the event. This should not be too costly, since it's just copying 8 floats between arrays with fixed indices.
Note: This patch does not include an updated build.
> Fix VRLayer bounds regression

- src/util.js
- src/webvr-polyfill.js
This addresses this bug in https://github.com/googlevr/webvr-polyfill/issues/177#issuecomment-282347327 and should complete #177.
The `VRFrameData` object is polyfilled on any cardboard-compatible (i.e. mobile) devices, even if it already exists. In the case where the cardboard device is polyfilled into a native WebVR implementation, `getFrameData` was throwing an error when trying to write data into a read-only `VRFrameData` object. This patch writes into a native object and then in turn copies into the polyfilled object.
I've tested this on Chrome/Cardboard with and without WebVR API enabled and with Vive and Daydream to make sure it doesn't interfere with a pure native implementation. But I recommend others test as well.
Please remember to update the build and version after accepting …
> Polyfill VRFrameData with Native API in case of no devices

- src/dpdb/dpdb-cache.js
We found that for one of our devices (a Samsung Note 5) the distortions were not being applied correctly, the reason being that the model number is "SM-N920W8" for Canadian devices.
> Add Note 5 user agent variant to Dpdb cache

- src/cardboard-vr-display.js
- src/dpdb/dpdb-cache.js
Pixel XL is in the database, however Pixel was not covered, and was logging "No DPDB device match".
Also I would like to recommend that https://storage.googleapis.com/cardboard-dpdb/dpdb.json be updated -- as of this pull request it is at least 2 versions behind (let me know if there should be a separate issue for this).
> Updated dpdb (adding Pixel)

- package.json
In order to run the `min` npm script one has to have `uglifyjs` on their machine. Ideally it is part of the dependencies like the other tools used.
> Add uglifyjs to dependencies

- src/cardboard-vr-display.js
This pull request is the same as #195 but with some additional comments added and no build file changes to make the merge easier since its seems like the original author is not updating the issue anymore.
It fixes a common issue (which can be see on the live webvr.info samples) introduced by #131 that happens if the page uses 'box-sizing: border-box' and the user enters VR from portrait mode.  Using border-box was causing the padding added by #131 to visible on both iOS and Android and breaking the cardboard setup and nullifying the intent of the fix. Border-box is a pretty common css reset trick these days so it is not uncommon to run into this issue. Visiting any of the webvr.info samples and entering VR from portrait on just about any mobile device will show the issue.
I have …
> Fix for visible padding when entering VR from portrait mode

- src/cardboard-ui.js
This fix slightly changes the way dps for the cardboard UI sizing is calculated for Android and iOS devices. When entering from portrait mode the screen.width will be the smaller dimension and this was throwing off the calculation. The code that was previously in place caused very large UI elements when entering from portrait on android devices. With this change, the same code works correctly on both iOS and Android devices. I also added some comments to explain the calculation a bit.
I've testing this a the following physical devices:
Pixel, Pixel XL, Nexus 5/6/5X/6P, Samsung S6, iPhone 5/6/7
as well as the iOS simulator for various devices.
> Fix for cardboard UI sizes when entering VR from portrait mode

- package.json
- test/index.js
In A-Frame, it is now possible to require aframe in node. This is useful for certain scenarios, such as isomorphic apps.
I would like to add a regression test that preserves the ability to require webvr-polyfill. We have something similar [here](https://github.com/aframevr/aframe/blob/master/tests/node/test.js#L32-L34).
cc @dmarcos @ngokevin
> add node require regression test

- src/dpdb/dpdb.js
Following on from the [comment](https://github.com/googlevr/webvr-polyfill/issues/184#issuecomment-293342108) by @toji recently, I am resubmitting this PR to point to the DPDB cache I have been maintaining.
I'm happy to keep it updated and will watch this repo for any requests to add new devices to it.
> Update online DPDB URL

- src/viewer-selector.js
Before, `this.selectedKey` would be `undefined` if `localStorage.getItem()` threw an error (such as if the user has disabled localStorage, is in Private mode, etc.).
This commit assigns the `DEFAULT_VIEWER` value in the cases of `localStorage.getItem()` returning `undefined` AND throwing an Error.
---
Without this, the viewer is also left `undefined`, and everything depending on it, such as creating new distortions (`this.distortion = new Distortion(this.viewer.distortionCoefficients)`) breaks. This has been the cause of issues for a few dozen users over the last few months.
> Make sure ViewerSelector.selectedKey always has a default value

- src/touch-panner.js
Fixes TypeError when touching Daydream trackpad caused by the fact
that Daydream controller creates an event object without a `touches`
property.
See https://github.com/aframevr/aframe/issues/2669 for background info.
This commit was based on https://github.com/googlevr/webvr-polyfill/commit/4787fe5546e33bb82b9a3981245f39d9e1e136ba
for a cleaner merge with https://github.com/aframevr/webvr-polyfill.
> Fix for Daydream controller touchstart: check for touches property before deep referencing

- .travis.yml
- test/index.js
At least one project consuming this in node supports all maintained node versions. Node 4 is still maintained https://github.com/nodejs/LTS#lts-schedule1. @jsantell could I convince you to keep regression testing node 4, so that any consumers don't unintentionally break?
> bring back node 4 regression testing

- package.json
- src/node-entry.js
- test/index.js
This will make it easier to run in node, and make the following code https://github.com/kellyselden/ember-aframe/blob/13a67e3d29d7af6f5d01f20ed1e5722096d38f6b/index.js#L16-L17 and https://github.com/aframevr/aframe/blob/cafbadc493701ebc5da33e531ea490e20a7eaa88/tests/node/test.js#L11-L12 obsolete.
> bolt on window vars to global in node

- package.json
- src/cardboard-vr-display.js
- src/util.js
- src/viewer-selector.js
Remove object-assign and eventemitter3 dependencies in lieu of inline, lighter functionality, and easier integration with Google build systems.
> Remove dependencies

- src/base.js
- src/webvr-polyfill.js
Note, `vrdisplaydisconnect` doesn't apply here as there's no way to remove a shim VRDisplay anyway.
> Fire 'vrdisplayconnect' event when populating VRDisplays. Fixes #40

- README.md
- src/main.js
- src/util.js
- src/webvr-polyfill.js
Still need to do some testing here to make sure this is the appropriate fix
> Set a timeout on getVRDisplays() to handle scenario where the promise never resolves. Fixes #199

- README.md
Very tiny README change that corrects a small syntax error where a comma is missing
> chore(readme): add comment to WebVRConfig def

- src/webvr-polyfill.js
To operate properly, the polyfill needs to load and run as early as possible. Even if WebVR API is available, `VRFrameData` is polyfilled in case the browser provides no displays and we need to create a polyfilled Cardboard display.
This patch fixes the case where a native `VRFrameData` instance is created before the polyfill can be applied. `VRDisplay.prototype.getFrameData` now checks its argument so it doesn't try to set the read-only `pose` property on a native object.
I've also taken the liberty of adding a reference to the original un-polyfilled `VRFrameData` as `WebVRPolyfill.prototype.NativeVRFrameData` in case someone wants to reference it.
Fixes #263
> Skip polyfilled `VRFrameData` if object passed to `getFrameData` is native

- webpack.config.js
It seems that WebPack tightened the security and the dev workflow I'm used to does not work anymore.
`npm start` and visiting `localhost:8080` locally or the `ip.of.my.server:8080` from a machine in my network returns an `Invalid Host header` error message. This PR disables the security host check on the `package.json` and everything works as it used to on my Windows boxes. The implications go a bit over my head so feel free to suggest an alternative. I found some literature here:
https://github.com/webpack/webpack-dev-server/issues/887
https://github.com/webpack/webpack-dev-server/issues/147#issuecomment-298816237
> Disable Host Check

- src/sensor-fusion/fusion-pose-sensor.js
Firefox for android returns the timestamp correctly now so there is no need to divide by 1000 any more.
> Fix fusion-pose-sensor.js for Firefox on Android

- src/webvr-polyfill.js
Don't try to modify navigator.vrEnabled if it does exist but is set to false. Check for undefined instead.  fix for github issue #280
> fix for github issue #280

- src/webvr-polyfill.js
If you run the polyfill when native VR is available, you won't be able to put the player into VR mode properly. This should fix https://github.com/borismus/webvr-boilerplate/issues/170 and https://github.com/videojs/videojs-vr/issues/14
> only run polyfill if nativeWebVR is not available

- src/cardboard-vr-display.js
via #282 
Need to test on an iOS device
> Use viewport sizes instead of pixels, and remove padding for cardboard VR display

- src/sensor-fusion/fusion-pose-sensor.js
- src/util.js
The changes here make the accelerometer / gyroscope based sensor fusion work properly on the latest Web Browser for the ODG R-7, which is a landscape-primary device.
> Make polyfill work with ODG R-7 Web Browser

- examples/basic/index.html
- Use clientWidth/clientHeight so page designer can size and place the canvas anywhere using CSS (not just fullscreen).
- Hides buttons when entering presentation mode (addresses issue https://github.com/googlevr/webvr-polyfill/issues/83)
> Use clientWidth/clientHeight instead of window.innerWidth/window.innerHeight

- src/util.js
When debug mode is activated on mobile devices, the polyfill throws a lot of errors:
```
Uncaught TypeError: Util.getQuaternionAngle is not a function
at ComplementaryFilter.run_ (webvr-polyfill.js:4237)
at ComplementaryFilter.addGyroMeasurement (webvr-polyfill.js:4190)
at FusionPoseSensor.updateDeviceMotion_ (webvr-polyfill.js:4039)
at FusionPoseSensor.onDeviceMotion_ (webvr-polyfill.js:4009)
```
Steps to reproduce:
1. Open http://googlevr.github.io/webvr-polyfill/examples/basic/?debug=true in Chrome on Android
2. Attach a remote Chrome debugger
3. Click the VR button
It appears that `Util.getQuaternionAngle` was (accidentally) removed some time [after v0.2.6](https://github.com/googlevr/webvr-polyfill/blob/v0.2.6/fusion/util.js), but it was still used in debug mode. This PR re-adds this …
> Re-add Util.getQuaternionAngle to fix debug mode

- src/webvr-polyfill.js
@brianchirls removing this fixes the issue in #258, and there are some other concerns regarding events there (maybe move into a new thread?), but this should do the trick on the connection event for the CardboardVRDisplay, whether or not it actually gets used
> Remove CardboardVRDisplay onvrdisplayconnect event, fixes #258

- src/config.js
- src/webvr-polyfill.js
and Chrome 58-60 are no longer in reasonable circulation. Fixes #335
@Artyom17 can you try this out and see if it works for you on Oculus?
> Remove GET_VR_DISPLAYS_TIMEOUT since it can lead to false positives
